version: '0.1.0'

# one service can start multiple containers
services:

  # defined service: cryptoarb
  cryptoarb:
    image: cryptoarb/prod
    stdin_open: true
    tty: true
    working_dir: /root/CryptoArb
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod

  # postgres-db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example
